language: node_js
node_js:
- 12.8.0
services:
- postgresql
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: BYVj/EM0rc6FoytpnPDAKYabY07QBWGYeG05ElXmf1cZcpHMkBJHh/Ze89kA7l1KWUP9r3Ss9fVu0mlzMzUXZy2lQrSc1TovuPBtCpMWsq8inmd47icaUzjKXScb1e8V944peykX5Me5IPzJjyJ1pZIaSwU/TW5x+tfeekHRXb7qbEycw3dzYTjHy1gXUK5dqUM1X9UAe3NF9V3AmECAlvUJ1mdQCyAWbBjQbs++TJxUhM+MEHB38sNqjQgewudl35VCJbV14319oTMPyOQ771BFcF+7hgP+89kVGawurttbTcMC/xZThCFRxixWnPXtSe/vykzRGAYkQb4X9Fww90rE0EeLwbJOCNIi7n6tPVE2FGjQZNXZf+y2BSwkG5yaKaE/iuTFro3tWa6kEO3RqEqeJxzaimdhmoLPEnzxE4qbEPOrt9ab2ZtWwxvhDsSBmyeOhMQ/HQ87m/YVGzV7UDxvtPpfLIkk97+ViIZM4nKr0GALCa8qhRlwwXV9PjsDvaVLSPsooH5lxXhimKo0zaohZhnO8f6zNHkFgSeLaRvh6UONMBFLfHoGrg7ZqhDIgDis2FcqxldO0k+qQ7fp8V1pcJW4lV/4ywRIKilancYk2mncC8+alduU9xPpAjjxgkJjPJMoetHfLnSQ13jv6zKpWvO6Xmc0BJSKHthvJOI=
  app: weatherforsweatersexpress
